### ISSUE TITLE
Remove btrack-reader from napari-hub/pypi

### ISSUE THREAD

**Issue by dpshelio** [lowe-lab-ucl/napari-btrack#22]
Once https://github.com/quantumjot/BayesianTracker/pull/115 is merged
pypi can't be removed, but we could make a new release that deprecates it

**Comment by paddyroddy** [comment]
This has been done. Closing as tracking in lowe-lab-ucl/napari-btrack-reader#4

**Comment by paddyroddy** [comment]
Reopening as you can't close an issue in an archived repo

**Comment by paddyroddy** [comment]
If I search for it, I can't find it, so I think this is done https://www.napari-hub.org/?search=napari-btrack-reader&sort=relevance&page=1
