### ISSUE TITLE
segmentation widget does not update with existing labels layers in the list

### ISSUE THREAD

**Issue by alessandrofelder** [lowe-lab-ucl/napari-btrack#31]
### how to reproduce
- open napari
- open or create a labels layer
- open the napari btrack widget added by #26 
- the dropdown menu for "segmentation" is empty, but should include the labels layer added in the first step.

**Comment by dstansby** [comment]
I've seen this in `cellfinder-napari` too. I think this is an issue with the `napari` integration with `magicgui` - when a widget is open, either `napari` or `magicgui` (I'm not sure which off the top of my head) should automatically populate the choices with existing layers, but doesn't. I would recommend making a minimal working example and opening a napari or magicgui issue.

**Comment by paddyroddy** [comment]
This appears to fixed via `magicgui` upgrading from `v0.4.0` to `v0.5.0`. @alessandrofelder and I have both verified this on our respective laptops with fresh `conda` environments. Closing now.
