### ISSUE TITLE
Fix linting on all 4 repos

### ISSUE THREAD

**Issue by paddyroddy** [lowe-lab-ucl/napari-btrack#42]

**Comment by p-j-smith** [comment]
closing as this was fixed in #43 and #45

**Comment by paddyroddy** [comment]
Sorry, this was lazy. I meant on `BayesianTracker`, `napari-btrack`, `napari-btrack-reader` and `arboretum` ideally.

**Comment by p-j-smith** [comment]
Ah sorry! I misread the issue name

**Comment by paddyroddy** [comment]
This has been done now 👌

**Comment by paddyroddy** [comment]
Fixed in quantumjot/btrack#224
